"""create first commit

Revision ID: 17f58748b155
Revises: 
Create Date: 2023-12-21 16:37:49.223426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f58748b155'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap', sa.Column('other_new', sa.Text(), nullable=True))
    op.execute('UPDATE nmap SET other_new = other')
    op.drop_column('nmap', 'other')
    op.alter_column('nmap', 'other_new', new_column_name='other', existing_nullable=True)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap', sa.Column('other_temp', sa.String(length=255), nullable=True))
    op.execute('UPDATE nmap SET other_temp = other')
    op.drop_column('nmap', 'other')
    op.alter_column('nmap', 'other_temp', new_column_name='other', existing_nullable=True)
    # ### end Alembic commands ###

