"""add data

Revision ID: 5128d2efe4ee
Revises: ab61c4f970f3
Create Date: 2023-12-19 17:34:35.760308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5128d2efe4ee'
down_revision: Union[str, None] = 'ab61c4f970f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('data_checked', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'data_checked')
    # ### end Alembic commands ###
