"""update type colummn OTHER str to TEXT

Revision ID: 7d2f1dd87ebf
Revises: 5128d2efe4ee
Create Date: 2023-12-19 17:40:00.495352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2f1dd87ebf'
down_revision: Union[str, None] = '5128d2efe4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap', sa.Column('other_new', sa.Text(), nullable=True))
    op.execute('UPDATE nmap SET other_new = other')
    op.drop_column('nmap', 'other')
    op.alter_column('nmap', 'other_new', new_column_name='other', existing_nullable=True)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nmap', 'other',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
