"""дада коли вимкнули пристрій

Revision ID: 9f08dad0790c
Revises: 365029bb7610
Create Date: 2024-01-04 13:49:01.436064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f08dad0790c'
down_revision: Union[str, None] = '365029bb7610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('data_status_down', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'data_status_down')
    # ### end Alembic commands ###
