"""дата коли телефонували на цей номер

Revision ID: bf85fc31eec4
Revises: 17f58748b155
Create Date: 2023-12-21 16:46:14.655356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf85fc31eec4'
down_revision: Union[str, None] = '17f58748b155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('data_call', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'data_call')
    # ### end Alembic commands ###
