"""додали значення дати закриття кейсу в форматі часу

Revision ID: c6f5f2dafe94
Revises: ef1c79ee5480
Create Date: 2023-12-21 15:11:22.340409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f5f2dafe94'
down_revision: Union[str, None] = 'ef1c79ee5480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('data_checked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'data_checked')
    # ### end Alembic commands ###
