"""додали таблицю frimware

Revision ID: e9f234c39878
Revises: bf85fc31eec4
Create Date: 2023-12-21 17:24:53.661459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f234c39878'
down_revision: Union[str, None] = 'bf85fc31eec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frimvare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_name', sa.String(length=50), nullable=True),
    sa.Column('new_version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frimvare')
    # ### end Alembic commands ###
