"""empty message

Revision ID: 82b91ed094ec
Revises: 
Create Date: 2023-11-08 23:42:05.728058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b91ed094ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=25), nullable=False),
    sa.Column('update', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('violation', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('looked', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('logscan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('ips', sa.String(length=25), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('other', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ips')
    )
    op.create_table('nmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('other', sa.String(length=255), nullable=True),
    sa.Column('id_address', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_address'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_address')
    )
    op.create_table('svmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ports', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('dev_name', sa.String(length=50), nullable=True),
    sa.Column('id_address', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_address'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('svmap')
    op.drop_table('nmap')
    op.drop_table('logscan')
    op.drop_table('address')
    # ### end Alembic commands ###
